# Generated by Django 4.2.16 on 2024-10-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da Empresa', max_length=70, verbose_name='Nome')),
                ('email', models.CharField(help_text='E-mail de contato', max_length=80, verbose_name='E-mail')),
                ('phone', models.CharField(help_text='Telefone de contato', max_length=15, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
    ]
