# Generated by Django 4.2.16 on 2024-10-09 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descrição do motivo da ausência', max_length=70, verbose_name='Descrição')),
                ('document_type', models.CharField(choices=[('cm', 'Consulta médica'), ('lp', 'Licença Paternidade'), ('ot', 'Outros')], default='cm', max_length=3, verbose_name='Tipo do documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
