# Generated by Django 4.2.16 on 2024-10-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('m', 'Consulta médica'), ('l', 'Licença Paternidade'), ('a', 'Aniversário'), ('o', 'outros')], default='m', max_length=3),
        ),
    ]
