# Generated by Django 4.2.16 on 2024-10-09 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do colaborador', max_length=70, verbose_name='Nome')),
                ('email', models.CharField(help_text='E-mail de contato', max_length=80, verbose_name='E-mail')),
                ('phone', models.CharField(help_text='Telefone de contato', max_length=15, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(to='departments.departments')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.enterprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['name'],
            },
        ),
    ]
